language: java
jdk:
  - oraclejdk8
before_install:
  - nvm install 6.9.1
  - wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-386-2.2.9.tgz
  - shasum -a 256 -c ./sha256.txt
  - tar -xvzf hub-linux-386-2.2.9.tgz
  - export PATH=$PWD/hub-linux-386-2.2.9/bin/:$PATH
  - nvm install 8.9.4
  - cd ./generator-spring
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run testint
  - npm run coveralls
  - ../deploy.sh
branches:
  only:
  - develop
  - master
